# Generated by Django 5.2.17 on 2026-08-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_backfill_teams_from_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='hide_branding',
            field=models.BooleanField(default=False),
        ),
    ]
