# Generated by Django 5.2.17 on 2026-08-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_hide_branding'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_comped',
            field=models.BooleanField(default=False, help_text='Manually granted Business Plan access by a super admin, bypassing payment.'),
        ),
    ]
