# Generated by Django 5.2.17 on 2026-08-09 04:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=32)),
                ('business_name', models.CharField(max_length=255)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(blank=True, max_length=11)),
                ('items', models.JSONField(default=list)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('due', 'Due')], default='due', max_length=4)),
                ('created_at_display', models.CharField(max_length=32)),
                ('paid_date_display', models.CharField(blank=True, max_length=32, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'invoice_number'), name='unique_invoice_number_per_user')],
            },
        ),
    ]
