# Generated by Django 5.2.17 on 2026-08-09 16:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('customer_name', models.CharField(max_length=255)),
                ('invoice_number', models.CharField(max_length=32)),
                ('items', models.JSONField(default=list)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('due', 'Due')], max_length=4)),
                ('created_at_display', models.CharField(max_length=32)),
                ('paid_date_display', models.CharField(blank=True, max_length=32, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_shares', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
