# Generated by Django 5.2.17 on 2026-08-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoiceshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='brand_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='invoice',
            name='note',
            field=models.CharField(blank=True, default='', max_length=280),
        ),
        migrations.AddField(
            model_name='invoiceshare',
            name='brand_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='invoiceshare',
            name='note',
            field=models.CharField(blank=True, default='', max_length=280),
        ),
    ]
