# Generated by Django 5.2.17 on 2026-08-13 05:05

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoice_brand_color_invoice_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceshare',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('partially_paid', 'Partially paid'), ('due', 'Due')], default='due', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoiceshare',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('partially_paid', 'Partially paid'), ('due', 'Due')], max_length=20),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_date_display', models.CharField(max_length=32)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoices.invoice')),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
    ]
