# Generated by Django 5.2.17 on 2026-08-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_alter_invoice_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceshare',
            name='hide_branding',
            field=models.BooleanField(default=False),
        ),
    ]
