# Generated by Django 5.2.17 on 2026-08-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_invoiceshare_hide_branding'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceshare',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=12, default=''),
        ),
    ]