# Generated by Django 5.2.17 on 2026-08-13 10:04

import django.db.models.deletion
import django.utils.timezone
import expenses.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('inventory', 'Inventory / stock'), ('transport', 'Transport'), ('rent', 'Rent'), ('utilities', 'Utilities'), ('salaries', 'Salaries / wages'), ('supplies', 'Supplies'), ('marketing', 'Marketing'), ('other', 'Other')], default='other', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=280)),
                ('expense_date', models.DateField(default=django.utils.timezone.localdate)),
                ('receipt', models.FileField(blank=True, null=True, upload_to=expenses.models.expense_receipt_path)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-expense_date', '-recorded_at'],
            },
        ),
    ]
