# Generated by Django 5.2.17 on 2026-08-13 16:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_number',
            field=models.CharField(default='EXP-OO1', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='title',
            field=models.CharField(default='EXP-001', max_length=255),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(fields=('user', 'expense_number'), name='unique_expense_number_per_user'),
        ),
    ]
