# Generated by Django 5.2.17 on 2026-08-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_invoice_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expense_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
