# Generated by Django 5.2.17 on 2026-08-24 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_email_verified'),
        ('teams', '0003_team_hide_branding'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='teams.team'),
        ),
    ]
